version: '3.9'

services:
  nodejs:
    build: .
    command: npm run watch
    ports:
      - 3333:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nono_network
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - nono_network
    environment:
      - MARIADB_DATABASE=NonolerobotDB
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=root

networks:
  nono_network:
    driver: bridge